// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// IntegrationListDevicesHandlerFunc turns a function with the right signature into a integration list devices handler
type IntegrationListDevicesHandlerFunc func(IntegrationListDevicesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IntegrationListDevicesHandlerFunc) Handle(params IntegrationListDevicesParams) middleware.Responder {
	return fn(params)
}

// IntegrationListDevicesHandler interface for that can handle valid integration list devices params
type IntegrationListDevicesHandler interface {
	Handle(IntegrationListDevicesParams) middleware.Responder
}

// NewIntegrationListDevices creates a new http.Handler for the integration list devices operation
func NewIntegrationListDevices(ctx *middleware.Context, handler IntegrationListDevicesHandler) *IntegrationListDevices {
	return &IntegrationListDevices{Context: ctx, Handler: handler}
}

/*IntegrationListDevices swagger:route GET /api/v1/integrations/devices integrationListDevices

IntegrationListDevices integration list devices API

*/
type IntegrationListDevices struct {
	Context *middleware.Context
	Handler IntegrationListDevicesHandler
}

func (o *IntegrationListDevices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewIntegrationListDevicesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
