// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Smart Tracking REST Server",
    "version": "1.0"
  },
  "paths": {
    "/api/v1/integrations/devices": {
      "get": {
        "security": [],
        "operationId": "integrationListDevices",
        "parameters": [
          {
            "enum": [
              "online",
              "offline"
            ],
            "type": "string",
            "name": "status",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Device"
              }
            }
          }
        }
      }
    },
    "/api/v1/integrations/devices/{deviceID}": {
      "get": {
        "security": [],
        "operationId": "integrationGetDevice",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Device"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "deviceID",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Device": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "string"
        },
        "fuelLevelLiters": {
          "type": "number",
          "format": "double"
        },
        "ignitionOn": {
          "type": "boolean"
        },
        "lat": {
          "type": "number",
          "format": "double"
        },
        "lon": {
          "type": "number",
          "format": "double"
        },
        "odometer": {
          "type": "number",
          "format": "double"
        },
        "status": {
          "type": "string",
          "enum": [
            "online",
            "offline"
          ]
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  },
  "securityDefinitions": {
    "isValidIntegration": {
      "type": "apiKey",
      "name": "x-smart-tracking-api-key",
      "in": "header"
    }
  },
  "security": [
    {
      "isValidIntegration": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Smart Tracking REST Server",
    "version": "1.0"
  },
  "paths": {
    "/api/v1/integrations/devices": {
      "get": {
        "security": [],
        "operationId": "integrationListDevices",
        "parameters": [
          {
            "enum": [
              "online",
              "offline"
            ],
            "type": "string",
            "name": "status",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Device"
              }
            }
          }
        }
      }
    },
    "/api/v1/integrations/devices/{deviceID}": {
      "get": {
        "security": [],
        "operationId": "integrationGetDevice",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Device"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "deviceID",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Device": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "string"
        },
        "fuelLevelLiters": {
          "type": "number",
          "format": "double"
        },
        "ignitionOn": {
          "type": "boolean"
        },
        "lat": {
          "type": "number",
          "format": "double"
        },
        "lon": {
          "type": "number",
          "format": "double"
        },
        "odometer": {
          "type": "number",
          "format": "double"
        },
        "status": {
          "type": "string",
          "enum": [
            "online",
            "offline"
          ]
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  },
  "securityDefinitions": {
    "isValidIntegration": {
      "type": "apiKey",
      "name": "x-smart-tracking-api-key",
      "in": "header"
    }
  },
  "security": [
    {
      "isValidIntegration": []
    }
  ]
}`))
}
